  0%|                                                                                                                                                                             | 0/100 [00:00<?, ?it/s]/home/jechmate/diffAE-elibeams/vae.py:205: UserWarning: Using a target size (torch.Size([64, 1, 256, 512])) that is different to the input size (torch.Size([128, 1, 256, 256])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  recon_loss = F.mse_loss(recon_x, x, reduction='sum')
  0%|                                                                                                                                                                             | 0/100 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/jechmate/diffAE-elibeams/vae.py", line 295, in <module>
    train()
  File "/home/jechmate/diffAE-elibeams/vae.py", line 246, in train
    loss, recon_loss, kld_loss = loss_function(recon_batch, inputs, mu, logvar)
  File "/home/jechmate/diffAE-elibeams/vae.py", line 205, in loss_function
    recon_loss = F.mse_loss(recon_x, x, reduction='sum')
  File "/home/jechmate/anaconda3/envs/eli/lib/python3.10/site-packages/torch/nn/functional.py", line 3291, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/jechmate/anaconda3/envs/eli/lib/python3.10/site-packages/torch/functional.py", line 74, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (256) must match the size of tensor b (512) at non-singleton dimension 3
